// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UrbanService.DAL.Data;

#nullable disable

namespace UrbanService.DAL.Migrations
{
    [DbContext(typeof(UrbanServiceDbContext))]
    [Migration("20260609082052_AddUserIsVerified")]
    partial class AddUserIsVerified
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("UrbanService.DAL.Entities.AiConversation", b =>
                {
                    b.Property<int>("AiConversationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ai_conversation_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AiConversationId"));

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ended_at");

                    b.Property<Guid?>("FeedbackId")
                        .HasColumnType("uuid")
                        .HasColumnName("feedback_id");

                    b.Property<DateTime>("StartedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'Active'::character varying");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("AiConversationId")
                        .HasName("ai_conversations_pkey");

                    b.HasIndex("FeedbackId");

                    b.HasIndex("UserId");

                    b.ToTable("ai_conversations", (string)null);
                });

            modelBuilder.Entity("UrbanService.DAL.Entities.AiKnowledgeSource", b =>
                {
                    b.Property<int>("KnowledgeSourceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("knowledge_source_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("KnowledgeSourceId"));

                    b.Property<int?>("CategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("category_id");

                    b.Property<string>("Content")
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("FileUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("file_url");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("source_type");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("KnowledgeSourceId")
                        .HasName("ai_knowledge_sources_pkey");

                    b.HasIndex("CategoryId");

                    b.ToTable("ai_knowledge_sources", (string)null);
                });

            modelBuilder.Entity("UrbanService.DAL.Entities.AiMessage", b =>
                {
                    b.Property<int>("AiMessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ai_message_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AiMessageId"));

                    b.Property<int>("AiConversationId")
                        .HasColumnType("integer")
                        .HasColumnName("ai_conversation_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("MessageText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message_text");

                    b.Property<string>("SenderType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("sender_type");

                    b.HasKey("AiMessageId")
                        .HasName("ai_messages_pkey");

                    b.HasIndex("AiConversationId");

                    b.ToTable("ai_messages", (string)null);
                });

            modelBuilder.Entity("UrbanService.DAL.Entities.AnalysisResult", b =>
                {
                    b.Property<int>("AnalysisResultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("analysis_result_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AnalysisResultId"));

                    b.Property<decimal?>("ConfidenceScore")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)")
                        .HasColumnName("confidence_score");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int?>("DetectedCategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("detected_category_id");

                    b.Property<Guid>("FeedbackId")
                        .HasColumnType("uuid")
                        .HasColumnName("feedback_id");

                    b.Property<string>("Keywords")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("keywords");

                    b.Property<string>("ModelName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("model_name");

                    b.Property<string>("RawResponse")
                        .HasColumnType("jsonb")
                        .HasColumnName("raw_response");

                    b.Property<string>("Sentiment")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("sentiment");

                    b.Property<string>("Summary")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("summary");

                    b.Property<string>("UrgencyLevel")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("urgency_level");

                    b.HasKey("AnalysisResultId")
                        .HasName("analysis_results_pkey");

                    b.HasIndex("DetectedCategoryId");

                    b.HasIndex("FeedbackId");

                    b.ToTable("analysis_results", (string)null);
                });

            modelBuilder.Entity("UrbanService.DAL.Entities.Channel", b =>
                {
                    b.Property<int>("ChannelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("channel_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ChannelId"));

                    b.Property<string>("ChannelName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("channel_name");

                    b.Property<string>("ExternalConversationId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("external_conversation_id");

                    b.Property<string>("ExternalMessageId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("external_message_id");

                    b.Property<Guid>("FeedbackId")
                        .HasColumnType("uuid")
                        .HasColumnName("feedback_id");

                    b.Property<DateTime>("ReceivedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("SourceUserExternalId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("source_user_external_id");

                    b.HasKey("ChannelId")
                        .HasName("channels_pkey");

                    b.HasIndex("FeedbackId");

                    b.ToTable("channels", (string)null);
                });

            modelBuilder.Entity("UrbanService.DAL.Entities.Feedback", b =>
                {
                    b.Property<Guid>("FeedbackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("feedback_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("approved_at");

                    b.Property<Guid?>("ApprovedByManagerId")
                        .HasColumnType("uuid")
                        .HasColumnName("approved_by_manager_id");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("category_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("due_date");

                    b.Property<bool>("IsMasterTicket")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_master_ticket");

                    b.Property<decimal?>("Latitude")
                        .HasPrecision(10, 7)
                        .HasColumnType("numeric(10,7)")
                        .HasColumnName("latitude");

                    b.Property<string>("LocationText")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("location_text");

                    b.Property<decimal?>("Longitude")
                        .HasPrecision(10, 7)
                        .HasColumnType("numeric(10,7)")
                        .HasColumnName("longitude");

                    b.Property<Guid?>("ParentTicketId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_ticket_id");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("priority")
                        .HasDefaultValueSql("'Medium'::character varying");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'Submitted'::character varying");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("FeedbackId")
                        .HasName("feedbacks_pkey");

                    b.HasIndex("ApprovedByManagerId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ParentTicketId");

                    b.HasIndex("UserId");

                    b.ToTable("feedbacks", (string)null);
                });

            modelBuilder.Entity("UrbanService.DAL.Entities.FeedbackAssignment", b =>
                {
                    b.Property<int>("AssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("assignment_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AssignmentId"));

                    b.Property<DateTime>("AssignedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assigned_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("AssignedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_by_user_id");

                    b.Property<string>("AssignmentStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("assignment_status")
                        .HasDefaultValueSql("'Assigned'::character varying");

                    b.Property<Guid>("FeedbackId")
                        .HasColumnType("uuid")
                        .HasColumnName("feedback_id");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("note");

                    b.Property<int>("OperatorId")
                        .HasColumnType("integer")
                        .HasColumnName("operator_id");

                    b.HasKey("AssignmentId")
                        .HasName("feedback_assignments_pkey");

                    b.HasIndex("AssignedByUserId");

                    b.HasIndex("FeedbackId");

                    b.HasIndex("OperatorId");

                    b.ToTable("feedback_assignments", (string)null);
                });

            modelBuilder.Entity("UrbanService.DAL.Entities.FeedbackAttachment", b =>
                {
                    b.Property<int>("AttachmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("attachment_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AttachmentId"));

                    b.Property<Guid>("FeedbackId")
                        .HasColumnType("uuid")
                        .HasColumnName("feedback_id");

                    b.Property<string>("FileType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("file_type");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("file_url");

                    b.Property<DateTime>("UploadedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploaded_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("AttachmentId")
                        .HasName("feedback_attachments_pkey");

                    b.HasIndex("FeedbackId");

                    b.ToTable("feedback_attachments", (string)null);
                });

            modelBuilder.Entity("UrbanService.DAL.Entities.FeedbackComment", b =>
                {
                    b.Property<int>("CommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("comment_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CommentId"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("FeedbackId")
                        .HasColumnType("uuid")
                        .HasColumnName("feedback_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("CommentId")
                        .HasName("feedback_comments_pkey");

                    b.HasIndex("FeedbackId");

                    b.HasIndex("UserId");

                    b.ToTable("feedback_comments", (string)null);
                });

            modelBuilder.Entity("UrbanService.DAL.Entities.FeedbackResolution", b =>
                {
                    b.Property<int>("ResolutionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("resolution_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ResolutionId"));

                    b.Property<string>("ActionTaken")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("action_taken");

                    b.Property<Guid>("FeedbackId")
                        .HasColumnType("uuid")
                        .HasColumnName("feedback_id");

                    b.Property<int>("OperatorId")
                        .HasColumnType("integer")
                        .HasColumnName("operator_id");

                    b.Property<string>("ResolutionSummary")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("resolution_summary");

                    b.Property<DateTime>("ResolvedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("ResolvedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("resolved_by_user_id");

                    b.Property<string>("ResultNote")
                        .HasColumnType("text")
                        .HasColumnName("result_note");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'SubmittedForApproval'::character varying");

                    b.HasKey("ResolutionId")
                        .HasName("feedback_resolutions_pkey");

                    b.HasIndex("FeedbackId");

                    b.HasIndex("OperatorId");

                    b.HasIndex("ResolvedByUserId");

                    b.ToTable("feedback_resolutions", (string)null);
                });

            modelBuilder.Entity("UrbanService.DAL.Entities.FeedbackResolutionAttachment", b =>
                {
                    b.Property<int>("ResolutionAttachmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("resolution_attachment_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ResolutionAttachmentId"));

                    b.Property<string>("FileType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("file_type");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("file_url");

                    b.Property<int>("ResolutionId")
                        .HasColumnType("integer")
                        .HasColumnName("resolution_id");

                    b.Property<DateTime>("UploadedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploaded_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("ResolutionAttachmentId")
                        .HasName("feedback_resolution_attachments_pkey");

                    b.HasIndex("ResolutionId");

                    b.ToTable("feedback_resolution_attachments", (string)null);
                });

            modelBuilder.Entity("UrbanService.DAL.Entities.FeedbackResolutionReview", b =>
                {
                    b.Property<int>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("review_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ReviewId"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("comment");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("FeedbackId")
                        .HasColumnType("uuid")
                        .HasColumnName("feedback_id");

                    b.Property<bool?>("IsSatisfied")
                        .HasColumnType("boolean")
                        .HasColumnName("is_satisfied");

                    b.Property<int?>("Rating")
                        .HasColumnType("integer")
                        .HasColumnName("rating");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("ReviewId")
                        .HasName("feedback_resolution_reviews_pkey");

                    b.HasIndex("FeedbackId");

                    b.HasIndex("UserId");

                    b.ToTable("feedback_resolution_reviews", (string)null);
                });

            modelBuilder.Entity("UrbanService.DAL.Entities.FeedbackStatusHistory", b =>
                {
                    b.Property<int>("HistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("history_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("HistoryId"));

                    b.Property<DateTime>("ChangedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("changed_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("ChangedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("changed_by_user_id");

                    b.Property<Guid>("FeedbackId")
                        .HasColumnType("uuid")
                        .HasColumnName("feedback_id");

                    b.Property<string>("NewStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("new_status");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("note");

                    b.Property<string>("OldStatus")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("old_status");

                    b.HasKey("HistoryId")
                        .HasName("feedback_status_histories_pkey");

                    b.HasIndex("ChangedByUserId");

                    b.HasIndex("FeedbackId");

                    b.ToTable("feedback_status_histories", (string)null);
                });

            modelBuilder.Entity("UrbanService.DAL.Entities.FeedbackSupport", b =>
                {
                    b.Property<int>("SupportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("support_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SupportId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("FeedbackId")
                        .HasColumnType("uuid")
                        .HasColumnName("feedback_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("SupportId")
                        .HasName("feedback_supports_pkey");

                    b.HasIndex("UserId");

                    b.HasIndex(new[] { "FeedbackId", "UserId" }, "uq_feedback_support_user")
                        .IsUnique();

                    b.ToTable("feedback_supports", (string)null);
                });

            modelBuilder.Entity("UrbanService.DAL.Entities.InteractionMessage", b =>
                {
                    b.Property<int>("InteractionMessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("interaction_message_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("InteractionMessageId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("FeedbackId")
                        .HasColumnType("uuid")
                        .HasColumnName("feedback_id");

                    b.Property<bool>("IsInternal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_internal");

                    b.Property<string>("MessageText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message_text");

                    b.Property<string>("SenderType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("sender_type");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("InteractionMessageId")
                        .HasName("interaction_messages_pkey");

                    b.HasIndex("FeedbackId");

                    b.HasIndex("UserId");

                    b.ToTable("interaction_messages", (string)null);
                });

            modelBuilder.Entity("UrbanService.DAL.Entities.MessageAttachment", b =>
                {
                    b.Property<int>("MessageAttachmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("message_attachment_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MessageAttachmentId"));

                    b.Property<string>("FileType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("file_type");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("file_url");

                    b.Property<int>("InteractionMessageId")
                        .HasColumnType("integer")
                        .HasColumnName("interaction_message_id");

                    b.Property<DateTime>("UploadedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploaded_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("MessageAttachmentId")
                        .HasName("message_attachments_pkey");

                    b.HasIndex("InteractionMessageId");

                    b.ToTable("message_attachments", (string)null);
                });

            modelBuilder.Entity("UrbanService.DAL.Entities.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("notification_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("NotificationId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_read");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<string>("TargetUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("target_url");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("NotificationId")
                        .HasName("notifications_pkey");

                    b.HasIndex("UserId");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("UrbanService.DAL.Entities.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RoleId"));

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("description");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("role_name");

                    b.HasKey("RoleId")
                        .HasName("roles_pkey");

                    b.HasIndex(new[] { "RoleName" }, "roles_role_name_key")
                        .IsUnique();

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("UrbanService.DAL.Entities.Service", b =>
                {
                    b.Property<int>("ServiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("service_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ServiceId"));

                    b.Property<decimal?>("BasePrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("base_price");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("category_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency")
                        .HasDefaultValueSql("'VND'::character varying");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<string>("ExternalServiceUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("external_service_url");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsSystemService")
                        .HasColumnType("boolean")
                        .HasColumnName("is_system_service");

                    b.Property<int>("OperatorId")
                        .HasColumnType("integer")
                        .HasColumnName("operator_id");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("service_name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("ServiceId")
                        .HasName("services_pkey");

                    b.HasIndex("CategoryId");

                    b.HasIndex(new[] { "OperatorId", "ServiceName" }, "uq_service_operator_name")
                        .IsUnique();

                    b.ToTable("services", (string)null);
                });

            modelBuilder.Entity("UrbanService.DAL.Entities.ServiceOperator", b =>
                {
                    b.Property<int>("OperatorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("operator_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("OperatorId"));

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("address");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("category_id");

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("contact_email");

                    b.Property<string>("ContactPhone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("contact_phone");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("OperatorName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("operator_name");

                    b.HasKey("OperatorId")
                        .HasName("service_operators_pkey");

                    b.HasIndex("CategoryId");

                    b.ToTable("service_operators", (string)null);
                });

            modelBuilder.Entity("UrbanService.DAL.Entities.ServicePayment", b =>
                {
                    b.Property<Guid>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("payment_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency")
                        .HasDefaultValueSql("'VND'::character varying");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("paid_at");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("payment_method");

                    b.Property<int>("ServiceId")
                        .HasColumnType("integer")
                        .HasColumnName("service_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'Pending'::character varying");

                    b.Property<string>("TransactionReference")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("transaction_reference");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("PaymentId")
                        .HasName("service_payments_pkey");

                    b.HasIndex("ServiceId");

                    b.HasIndex("UserId");

                    b.HasIndex(new[] { "TransactionReference" }, "uq_service_payment_transaction_reference")
                        .IsUnique();

                    b.ToTable("service_payments", (string)null);
                });

            modelBuilder.Entity("UrbanService.DAL.Entities.UrbanServiceCategory", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("category_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("category_name");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.HasKey("CategoryId")
                        .HasName("urban_service_categories_pkey");

                    b.ToTable("urban_service_categories", (string)null);
                });

            modelBuilder.Entity("UrbanService.DAL.Entities.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("user_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("address");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("avatar_url");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsRefreshTokenRevoked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_refresh_token_revoked");

                    b.Property<bool>("IsVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_verified");

                    b.Property<int?>("OperatorId")
                        .HasColumnType("integer")
                        .HasColumnName("operator_id");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone_number");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text")
                        .HasColumnName("refresh_token");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("UserId")
                        .HasName("users_pkey");

                    b.HasIndex("OperatorId");

                    b.HasIndex("RoleId");

                    b.HasIndex(new[] { "Email" }, "users_email_key")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("UrbanService.DAL.Entities.AiConversation", b =>
                {
                    b.HasOne("UrbanService.DAL.Entities.Feedback", "Feedback")
                        .WithMany("AiConversations")
                        .HasForeignKey("FeedbackId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_ai_conversation_feedback");

                    b.HasOne("UrbanService.DAL.Entities.User", "User")
                        .WithMany("AiConversations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ai_conversation_user");

                    b.Navigation("Feedback");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UrbanService.DAL.Entities.AiKnowledgeSource", b =>
                {
                    b.HasOne("UrbanService.DAL.Entities.UrbanServiceCategory", "Category")
                        .WithMany("AiKnowledgeSources")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_knowledge_source_category");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("UrbanService.DAL.Entities.AiMessage", b =>
                {
                    b.HasOne("UrbanService.DAL.Entities.AiConversation", "AiConversation")
                        .WithMany("AiMessages")
                        .HasForeignKey("AiConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ai_message_conversation");

                    b.Navigation("AiConversation");
                });

            modelBuilder.Entity("UrbanService.DAL.Entities.AnalysisResult", b =>
                {
                    b.HasOne("UrbanService.DAL.Entities.UrbanServiceCategory", "DetectedCategory")
                        .WithMany("AnalysisResults")
                        .HasForeignKey("DetectedCategoryId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_analysis_result_category");

                    b.HasOne("UrbanService.DAL.Entities.Feedback", "Feedback")
                        .WithMany("AnalysisResults")
                        .HasForeignKey("FeedbackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_analysis_result_feedback");

                    b.Navigation("DetectedCategory");

                    b.Navigation("Feedback");
                });

            modelBuilder.Entity("UrbanService.DAL.Entities.Channel", b =>
                {
                    b.HasOne("UrbanService.DAL.Entities.Feedback", "Feedback")
                        .WithMany("Channels")
                        .HasForeignKey("FeedbackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_channel_feedback");

                    b.Navigation("Feedback");
                });

            modelBuilder.Entity("UrbanService.DAL.Entities.Feedback", b =>
                {
                    b.HasOne("UrbanService.DAL.Entities.User", "ApprovedByManager")
                        .WithMany("FeedbackApprovedByManagers")
                        .HasForeignKey("ApprovedByManagerId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_feedback_manager");

                    b.HasOne("UrbanService.DAL.Entities.UrbanServiceCategory", "Category")
                        .WithMany("Feedbacks")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_feedback_category");

                    b.HasOne("UrbanService.DAL.Entities.Feedback", "ParentTicket")
                        .WithMany("InverseParentTicket")
                        .HasForeignKey("ParentTicketId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_feedback_parent");

                    b.HasOne("UrbanService.DAL.Entities.User", "User")
                        .WithMany("FeedbackUsers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_feedback_user");

                    b.Navigation("ApprovedByManager");

                    b.Navigation("Category");

                    b.Navigation("ParentTicket");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UrbanService.DAL.Entities.FeedbackAssignment", b =>
                {
                    b.HasOne("UrbanService.DAL.Entities.User", "AssignedByUser")
                        .WithMany("FeedbackAssignments")
                        .HasForeignKey("AssignedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_feedback_assignment_assigned_by");

                    b.HasOne("UrbanService.DAL.Entities.Feedback", "Feedback")
                        .WithMany("FeedbackAssignments")
                        .HasForeignKey("FeedbackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_feedback_assignment_feedback");

                    b.HasOne("UrbanService.DAL.Entities.ServiceOperator", "Operator")
                        .WithMany("FeedbackAssignments")
                        .HasForeignKey("OperatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_feedback_assignment_operator");

                    b.Navigation("AssignedByUser");

                    b.Navigation("Feedback");

                    b.Navigation("Operator");
                });

            modelBuilder.Entity("UrbanService.DAL.Entities.FeedbackAttachment", b =>
                {
                    b.HasOne("UrbanService.DAL.Entities.Feedback", "Feedback")
                        .WithMany("FeedbackAttachments")
                        .HasForeignKey("FeedbackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_feedback_attachment_feedback");

                    b.Navigation("Feedback");
                });

            modelBuilder.Entity("UrbanService.DAL.Entities.FeedbackComment", b =>
                {
                    b.HasOne("UrbanService.DAL.Entities.Feedback", "Feedback")
                        .WithMany("FeedbackComments")
                        .HasForeignKey("FeedbackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_feedback_comment_feedback");

                    b.HasOne("UrbanService.DAL.Entities.User", "User")
                        .WithMany("FeedbackComments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_feedback_comment_user");

                    b.Navigation("Feedback");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UrbanService.DAL.Entities.FeedbackResolution", b =>
                {
                    b.HasOne("UrbanService.DAL.Entities.Feedback", "Feedback")
                        .WithMany("FeedbackResolutions")
                        .HasForeignKey("FeedbackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_feedback_resolution_feedback");

                    b.HasOne("UrbanService.DAL.Entities.ServiceOperator", "Operator")
                        .WithMany("FeedbackResolutions")
                        .HasForeignKey("OperatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_feedback_resolution_operator");

                    b.HasOne("UrbanService.DAL.Entities.User", "ResolvedByUser")
                        .WithMany("FeedbackResolutions")
                        .HasForeignKey("ResolvedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_feedback_resolution_user");

                    b.Navigation("Feedback");

                    b.Navigation("Operator");

                    b.Navigation("ResolvedByUser");
                });

            modelBuilder.Entity("UrbanService.DAL.Entities.FeedbackResolutionAttachment", b =>
                {
                    b.HasOne("UrbanService.DAL.Entities.FeedbackResolution", "Resolution")
                        .WithMany("FeedbackResolutionAttachments")
                        .HasForeignKey("ResolutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_resolution_attachment_resolution");

                    b.Navigation("Resolution");
                });

            modelBuilder.Entity("UrbanService.DAL.Entities.FeedbackResolutionReview", b =>
                {
                    b.HasOne("UrbanService.DAL.Entities.Feedback", "Feedback")
                        .WithMany("FeedbackResolutionReviews")
                        .HasForeignKey("FeedbackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_resolution_review_feedback");

                    b.HasOne("UrbanService.DAL.Entities.User", "User")
                        .WithMany("FeedbackResolutionReviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_resolution_review_user");

                    b.Navigation("Feedback");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UrbanService.DAL.Entities.FeedbackStatusHistory", b =>
                {
                    b.HasOne("UrbanService.DAL.Entities.User", "ChangedByUser")
                        .WithMany("FeedbackStatusHistories")
                        .HasForeignKey("ChangedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_status_history_user");

                    b.HasOne("UrbanService.DAL.Entities.Feedback", "Feedback")
                        .WithMany("FeedbackStatusHistories")
                        .HasForeignKey("FeedbackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_status_history_feedback");

                    b.Navigation("ChangedByUser");

                    b.Navigation("Feedback");
                });

            modelBuilder.Entity("UrbanService.DAL.Entities.FeedbackSupport", b =>
                {
                    b.HasOne("UrbanService.DAL.Entities.Feedback", "Feedback")
                        .WithMany("FeedbackSupports")
                        .HasForeignKey("FeedbackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_feedback_support_feedback");

                    b.HasOne("UrbanService.DAL.Entities.User", "User")
                        .WithMany("FeedbackSupports")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_feedback_support_user");

                    b.Navigation("Feedback");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UrbanService.DAL.Entities.InteractionMessage", b =>
                {
                    b.HasOne("UrbanService.DAL.Entities.Feedback", "Feedback")
                        .WithMany("InteractionMessages")
                        .HasForeignKey("FeedbackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_interaction_message_feedback");

                    b.HasOne("UrbanService.DAL.Entities.User", "User")
                        .WithMany("InteractionMessages")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_interaction_message_user");

                    b.Navigation("Feedback");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UrbanService.DAL.Entities.MessageAttachment", b =>
                {
                    b.HasOne("UrbanService.DAL.Entities.InteractionMessage", "InteractionMessage")
                        .WithMany("MessageAttachments")
                        .HasForeignKey("InteractionMessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_message_attachment_interaction_message");

                    b.Navigation("InteractionMessage");
                });

            modelBuilder.Entity("UrbanService.DAL.Entities.Notification", b =>
                {
                    b.HasOne("UrbanService.DAL.Entities.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_notification_user");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UrbanService.DAL.Entities.Service", b =>
                {
                    b.HasOne("UrbanService.DAL.Entities.UrbanServiceCategory", "Category")
                        .WithMany("Services")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_service_category");

                    b.HasOne("UrbanService.DAL.Entities.ServiceOperator", "Operator")
                        .WithMany("Services")
                        .HasForeignKey("OperatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_service_operator");

                    b.Navigation("Category");

                    b.Navigation("Operator");
                });

            modelBuilder.Entity("UrbanService.DAL.Entities.ServiceOperator", b =>
                {
                    b.HasOne("UrbanService.DAL.Entities.UrbanServiceCategory", "Category")
                        .WithMany("ServiceOperators")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_service_operator_category");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("UrbanService.DAL.Entities.ServicePayment", b =>
                {
                    b.HasOne("UrbanService.DAL.Entities.Service", "Service")
                        .WithMany("ServicePayments")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_service_payment_service");

                    b.HasOne("UrbanService.DAL.Entities.User", "User")
                        .WithMany("ServicePayments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_service_payment_user");

                    b.Navigation("Service");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UrbanService.DAL.Entities.User", b =>
                {
                    b.HasOne("UrbanService.DAL.Entities.ServiceOperator", "Operator")
                        .WithMany("Users")
                        .HasForeignKey("OperatorId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_user_operator");

                    b.HasOne("UrbanService.DAL.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_user_role");

                    b.Navigation("Operator");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("UrbanService.DAL.Entities.AiConversation", b =>
                {
                    b.Navigation("AiMessages");
                });

            modelBuilder.Entity("UrbanService.DAL.Entities.Feedback", b =>
                {
                    b.Navigation("AiConversations");

                    b.Navigation("AnalysisResults");

                    b.Navigation("Channels");

                    b.Navigation("FeedbackAssignments");

                    b.Navigation("FeedbackAttachments");

                    b.Navigation("FeedbackComments");

                    b.Navigation("FeedbackResolutionReviews");

                    b.Navigation("FeedbackResolutions");

                    b.Navigation("FeedbackStatusHistories");

                    b.Navigation("FeedbackSupports");

                    b.Navigation("InteractionMessages");

                    b.Navigation("InverseParentTicket");
                });

            modelBuilder.Entity("UrbanService.DAL.Entities.FeedbackResolution", b =>
                {
                    b.Navigation("FeedbackResolutionAttachments");
                });

            modelBuilder.Entity("UrbanService.DAL.Entities.InteractionMessage", b =>
                {
                    b.Navigation("MessageAttachments");
                });

            modelBuilder.Entity("UrbanService.DAL.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("UrbanService.DAL.Entities.Service", b =>
                {
                    b.Navigation("ServicePayments");
                });

            modelBuilder.Entity("UrbanService.DAL.Entities.ServiceOperator", b =>
                {
                    b.Navigation("FeedbackAssignments");

                    b.Navigation("FeedbackResolutions");

                    b.Navigation("Services");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("UrbanService.DAL.Entities.UrbanServiceCategory", b =>
                {
                    b.Navigation("AiKnowledgeSources");

                    b.Navigation("AnalysisResults");

                    b.Navigation("Feedbacks");

                    b.Navigation("ServiceOperators");

                    b.Navigation("Services");
                });

            modelBuilder.Entity("UrbanService.DAL.Entities.User", b =>
                {
                    b.Navigation("AiConversations");

                    b.Navigation("FeedbackApprovedByManagers");

                    b.Navigation("FeedbackAssignments");

                    b.Navigation("FeedbackComments");

                    b.Navigation("FeedbackResolutionReviews");

                    b.Navigation("FeedbackResolutions");

                    b.Navigation("FeedbackStatusHistories");

                    b.Navigation("FeedbackSupports");

                    b.Navigation("FeedbackUsers");

                    b.Navigation("InteractionMessages");

                    b.Navigation("Notifications");

                    b.Navigation("ServicePayments");
                });
#pragma warning restore 612, 618
        }
    }
}
